#!/bin/bash

# Get the database connections
source $HOME/.bash_profile

NODE=/usr/bin/node
TMP_FILE=/tmp/groupCatalogFeatures.json
TARGET_FILE=/var/www/placenames/placenames/resources/config/groupCatalogFeatures.json
MIN_SIZE=80

# Generate the refrence data from the PostGis table

cd /home/ec2-user/elvis-placenames/deployment

# Build it somewhere where we can inspect it prior to copying.
$NODE build_reference_data.js > $TMP_FILE

# Test file size. We are better off with an old version rather than a broken version
ACTUAL_SIZE=$(du -k "$TMP_FILE" | cut -f 1)
if [ $ACTUAL_SIZE -ge $MIN_SIZE ]; then
   # Copy the content to Apache.
   sudo rm -f $TARGET_FILE
   sudo cp $TMP_FILE $TARGET_FILE
else
   echo size is under $MIN_SIZE kilobytes
fi

